services:
  backend:
    build: null #overrides 'build: ./backend' from docker-compose.yml
    image: node:25.2-alpine3.23 #use base image instead
    working_dir: /app
    volumes:
      - ./backend:/app #mount source code for live reload
      - backend-node-modules:/app/node_modules
      - ./Test:/app/storage #local test storage folder
    environment:
      NODE_ENV: development
      TEST_DATABASE_URL: postgresql://test_user:test_pw@test_postgres_db:5432/test_db
    command: sh -c "npm install && npx nodemon --exec ts-node server.ts"
  
  test_postgres_db:
    image: postgres:18-alpine3.23
    restart: unless-stopped
    shm_size: 128mb #shared memory limit
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pw
      PGDATA: /var/lib/postgresql/18/data
    volumes:
      - postgres-test-data:/var/lib/postgresql/18/data
      - ./postgres-db/init:/docker-entrypoint-initdb.d  # init/schema.sql
    #ports:
    #  - "5432:5432"
    networks:
      - nas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5  

  nginx:
    build: null
    image: nginx:stable-alpine3.23-perl
    volumes:
      - ./nginx/templates/default.dev.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - DOMAIN=${DOMAIN}
    ports:
     - "${NETWORK_IP}:80:80"
    extra_hosts:
    - "host.docker.internal:host-gateway" #allows to link the frontend (before containerizing it) to nginx

volumes:
  backend-node-modules:
  postgres-test-data: