name: nas
services:

  nginx:
    volumes:
      - ./nginx/templates/default.ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "${NETWORK_IP}:80:80"
      - "${NETWORK_IP}:443:443"
    networks:
      - nas