name: nas
services:

  nginx:
    volumes:
      - ./nginx/templates/default.http.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "${NETWORK_IP}:80:80"
      - "${NETWORK_IP}:443:443"
    networks:
      - nas