events {
    worker_connections 1024; #nr of simultaneous connections a worker can take. Overkill, but default
}

http {
    include /etc/nginx/mime.types; #MIME types tell browsers what kind of file they're getting
    default_type application/octet-stream; #if nginx doesn't know the type, use this generic one

    #BASICS
    sendfile on; #efficient file sending
    keepalive_timeout 65; #keep connections alive for 65 seconds (faster for repeated requests)
    client_max_body_size 100M;  #max file upload size

    #LOGGING
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    #include additional configs from conf.d folder
    include /etc/nginx/conf.d/*.conf;
}